### ISSUE TITLE
Failed decode with large binary data

### ISSUE THREAD

**Issue by icebob** [kriszyp/cbor-x#1]
Hi,

There is an issue when I try to encode/decode a larger `Buffer` data. _The same data works with MsgPack._

I made a repro example on repl.it: https://replit.com/@icebob/cbor-issue#index.js

![image](https://user-images.githubusercontent.com/306521/118323762-6d671900-b501-11eb-87f1-b1d0ca798e28.png)

**Comment by kriszyp** [comment]
OK, thanks for the great test case, there are some fixes I am working on porting over, so will make sure they address this issue.

**Comment by kriszyp** [comment]
I believe this should be fixed in v0.8 (let me know if you still see the issue).

**Comment by icebob** [comment]
Thanks, the repl.it works, but in the project, now I got a warning:
![image](https://user-images.githubusercontent.com/306521/118444539-8a603f80-b6ed-11eb-9530-fc0f84f65613.png)
Could you explain what it means?

**Comment by kriszyp** [comment]
This should be fixed with v0.8.2.

**Comment by icebob** [comment]
Thanks, now it looks fine! 
If you have time, could you make a `changelog.md` that I will able to check it (instead of commits) at upgrading in the future? :)

Keep up the good work!
