### ISSUE TITLE
Segmentation Fault in Deno >= 1.44.2

### ISSUE THREAD

**Issue by Hexagon** [kriszyp/cbor-x#110]
I've encontered an issue with any version of cbor-x in Deno versions 1.44.2 and later. A segmentation fault (or intermittently a runtime error) is triggered by specific data structures, such as the example provided below. The issue does not occur if the encoded result is immediately decoded without any intermediate steps (e.g., decode(encode(obj))).

**Minimal repro: `test.ts`**
```ts 
import { decode, encode } from "npm:cbor-x@1.5.9";
// - In Deno 1.44.2, 100 repeatitions is fine, 200 gives typeError
// - In Deno 1.44.1 - everything is fine
decode(new Uint8Array(encode({"a":"a".repeat(200)})));
```

**Output:**
```
> deno run -A test.ts

error: Uncaught (in promise) TypeError: Unexpected end of buffer reading string
    at readString (file:///.../.deno/cbor-x@1.5.9/node_modules/cbor-x/decode.js:531:22)
```

**Segmentation fault repro: `test2.ts`**
```ts
import { decode, encode } from "npm:cbor-x@1.5.9";
for(let i=0; i < 1000; i++) {
  try {
    decode(new Uint8Array(encode({"a":"a".repeat(200000)})));
  } catch (_e) { /* Ignore */}
}
```

**Output:**
```
> deno run -A test2.ts

Segmentation fault (core dumped)
```

Tested on Windows

```
deno 1.44.2 (release, x86_64-pc-windows-msvc)
v8 12.6.228.9
typescript 5.4.5
```

And Linux

```
deno 1.44.4 (release, x86_64-unknown-linux-gnu)
v8 12.6.228.9
typescript 5.4.5
```

**Comment by kriszyp** [comment]
Looks like Deno is going to fix this.

**Comment by Hexagon** [comment]
This is no longer a problem since Deno `1.45.x`
