### ISSUE TITLE
decoding and re-encoding an object results in different Uint8Array's

### ISSUE THREAD

**Issue by aegatlin** [kriszyp/cbor-x#114]
Hello 👋 

I am struggling to figure out how to get the right Uint8Array encoding sent to my client (and ios app in Swift). The hard-coded `bytes1` can be encoded and decoded on my Swift client cbor implementation, and `cbor-x` can decode those bytes correctly, as seen by `obj1`. But, if I re-encode it and send it back, I end up receiving `bytes2` on the client, which it cannot decode.

I have read the documentation but I cannot figure out what to do. I suspect it might have something to do with objects/maps/records/etc, but I'm not confident.

For some additional context: The message type itself is wrapping yet another Uint8Array which is not cbor-encoded.

```js
const c = require("cbor-x");

const bytes1 = new Uint8Array([
  162, 97, 97, 100, 116, 101, 115, 116, 97, 98, 131, 24, 98, 24, 104, 24, 105,
]);
console.log(bytes1)
/*
Uint8Array(17) [
  162,  97,  97, 100, 116, 101,
  115, 116,  97,  98, 131,  24,
  98,  24, 104,  24, 105
]
 */
const obj1 = c.decode(bytes1);
console.log(obj1);
// { a: 'test', b: [ 98, 104, 105 ] }





const buffer2 = c.encode(obj1);
const bytes2 = new Uint8Array(buffer2);
console.log(bytes2)
/*
Uint8Array(19) [
  185,   0,   2,  97,  97, 100,
  116, 101, 115, 116,  97,  98,
  131,  24,  98,  24, 104,  24,
  105
]
*/
const obj2 = c.decode(bytes2);
console.log(obj2)
// { a: 'test', b: [ 98, 104, 105 ] }


```

**Comment by atomictag** [comment]
Your bytes1 array contains a Map (probably the way Swift deal with records - since it has no notion of "objects").

bytes1 In hex: a261616474657374616283186218681869
which you can paste here here https://cbor.nemo157.com/ (click on "Annotate") 
to see how it looks like 

Now try this 

```typescript
import { Encoder } from "cbor-x";

const c = new Encoder({
      mapsAsObjects: false,
});

const obj1 = c.decode(bytes1);
console.log(obj1);

// Map(2) { 'a' => 'test', 'b' => [ 98, 104, 105 ] }
```

Note that your decoded thing is a Map, not a record:
Your encoded buffer2 / bytes2 will now look exactly as bytes1

**Comment by aegatlin** [comment]
Thank you @atomictag! I just learned a lot from your reply ❤️ 

Here's my understanding now: By default `cbor-x` was decoding `bytes1` into a `Map` and then turning that `Map` into an `Object` because by default `mapsAsObjects` is `true`. This explains the different byte arrays and the failure to parse it on the Swift client. 

And the fix is (1) telling `cbor-x` _not_ to turn `Map`s to `Object`s by setting `mapsAsObjects` to `false`, and (2) only encoding actual `Map`s on the server. This will maximize compatibility.

I believe this resolves my dilemma. Thank you very much for the fast and informative reply 🙏

**Comment by atomictag** [comment]
Glad it worked.

> And the fix is (1) telling `cbor-x` _not_ to turn `Map`s to `Object`s by setting `mapsAsObjects` to `false`, and (2) only encoding actual `Map`s on the server. This will maximize compatibility.

Yeh I believe a new Encoder is always setup with `mapsAsObjects = false` but I made it explicit.

`cbor-x` has the peculiarity that the default encoder (the one you were using) and a custom Encoder that is created from scratch are configured differently and it's not always super obvious how. I think the default encoder has `useRecords=false` and `mapsAsObjects = true`, while custom encoders by default have `useRecords=true` and `mapsAsObjects = false`. 

Your best bet is probably to use a custom Encoder(s) and then apply selectively the options in the docs to tune your setup depending on your needs.  Enjoy! CBOR is cool.
