### ISSUE TITLE
`structuredClone` - "preserving certain typed objects"?

### ISSUE THREAD

**Issue by josephrocca** [kriszyp/cbor-x#115]
This is a *really* nice package, and thank you so much for the excellent documentation! I just had one question about the docs on `structuredClone`:

> Structured cloning also enables preserving certain typed objects like `Error`, `Set`, `RegExp` and `TypedArray` instances, using [registered CBOR tag extensions](https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml).

I noticed that `Set` is encoded without error even without the `structuredClone` option, so I think I may be misunderstanding. Is this perhaps about preserving *references*? That was my fallback interpretation, but if that were true, then I'm wondering why `Set`, `RegExp`, etc. are specifically called out here? IIUC, references aren't preserved at all unless `structuredClone` is true, so even something like a POJO/Object wouldn't have its reference preserved. So I'm not sure that my fallback interpretation makes sense here.

**Comment by kriszyp** [comment]
Yes, `structuredClone` is only about preserving references. I will update the docs. The reason that was in there, is because it was forked from the msgpackr package that does have different behavior for Set, Map, etc.

**Comment by josephrocca** [comment]
Ah, gotcha, thank you!
