### ISSUE TITLE
CBOR maps generated by this module cannot be read by nlohmann/json

### ISSUE THREAD

**Issue by LAX1DUDE** [kriszyp/cbor-x#13]
I am using CBOR to encode messages between my client and server in this game I'm making. I'm using this module on the server to serialize and on the client I am using nlohmann/json to parse. The client is C++ and the server is JavaScript. When I console.log the packet I am trying to send I get these bytes:

`<Buffer d8 69 90 8e 63 70 6b 74 64 74 69 6d 65 66 63 6c 6f 75 64 58 66 63 6c 6f 75 64 5a 65 77 69 6e 64 58 65 77 69 6e 64 5a 62 69 64 61 78 61 79 61 7a 63 79 ... 63 more bytes>`

But then when the bytes start to be parsed on the other side by nlohmann/json it fails with this message:
`13:15:56+334: ERROR - Socket: Could not decode packet: [json.exception.parse_error.112] parse error at byte 1: syntax error while parsing CBOR value: invalid byte: 0xD8`

I just need some help understanding how to configure this library to create valid CBOR, I've tried the `objectsAsMaps: true` and `variableMapSize: true` and `useRecords: false` in different combinations and it has not changed the resulting behavior

**Comment by kriszyp** [comment]
Can you send me a sample of how you are doing this? If I simply do `require('cbor-x').encode({test: 1})` or `let e = new Encoder({useRecords: false}); e.encode({test:1})`, I get an encoding that begins with 0xb9 (map).

**Comment by LAX1DUDE** [comment]
Quick update, with `objectsAsMaps: true` and `useRecords: true` it parses to byte 92 instead of byte 1:
`[json.exception.parse_error.112] parse error at byte 92: syntax error while parsing CBOR value: invalid byte: 0xF7`

I create the encoder using:
`const cbor = new cborx.Encoder({ useFloat32: cborx.DECIMAL_FIT, objectsAsMaps: true, useRecords: false  });`

Decimal fit is the whole reason I'm using this module over others, I already tried disabling it and it was not the problem

I encode and send using:
```
newConnection.websocket.send(cbor.encode({
	"pkt": "handshake",
	"time": server.world.localTime,
	"cloudX": server.world.cloudX,
	"cloudZ": server.world.cloudZ,
	"windX": server.world.windX,
	"windZ": server.world.windZ,
	"id": newConnection.entityId,
	"x": newConnection.posX,
	"y": newConnection.posY,
	"z": newConnection.posZ,
	"yaw": newConnection.playerYaw,
	"px": newConnection.physicsOffsetX,
	"py": newConnection.physicsOffsetY,
	"pz": newConnection.physicsOffsetZ
}));
```

On the other side, I parse using:
```
static void onMessage(wsClientType* c, websocketpp::connection_hdl hdl, wsClientMessagePtr msg) {
	if (msg->get_opcode() == websocketpp::frame::opcode::BINARY) {
		string rp = msg->get_raw_payload();
		try {
			handlePacket(json::from_cbor(rp.c_str(), rp.c_str() + rp.size(), false, true));
		}
		catch (const exception& e) {
			eLOG(logERROR, "Socket", "Could not decode packet: %s: %s", e.what(), rp.c_str());
		}
	}
	else {
		dg(msg->get_payload().c_str());
	}
}
```

**Comment by LAX1DUDE** [comment]
Solution: nlohmann/json does not support the 'undefined' data type [https://gyazo.com/6b0a6368aa939b6dde9b970dde03df68](https://gyazo.com/6b0a6368aa939b6dde9b970dde03df68) and one of my variables was undefined so it was failing to parse

**Comment by kriszyp** [comment]
Ah, so it was tripping up on the 0xf7 (the byte code for `undefined`)? I guess if you think it would help, could add an option to disable/warn  about `undefined` usage, I suppose, but sounds like this is resolved for you.
