### ISSUE TITLE
Cbor-x isn't Websocket friendly

### ISSUE THREAD

**Issue by Kamil93** [kriszyp/cbor-x#15]
```
this.cborEncoder = new CBOR.Encoder({useRecords: false, useTag259ForMaps: false});

const encoded:  Uint8Array  = this.cborEncoder.encode(event);
const decoded:  Uint8Array  = this.cborEncoder.decode(encoded);

//'decoded' is the same as 'event' and zero error occured, so success!
```

That example works very well, but when you try to send `encoded` through Engine.io/Socket.io to server, it sends whole ArrayBuffer (~8.2kB), so I'll tried this:

```
const encoded:  Uint8Array  = this.cborEncoder.encode(event);
const decoded:  Uint8Array  = this.cborEncoder.decode(encoded);
const encoded_trimmed = new Uint8Array(encoded.buffer.slice(encoded.byteOffset, encoded.byteLength));
```

But then backend somtimes successfully decode message, sometimes yells Error:

`Error: Unexpected end of buffer reading string`

or

`Unexpected end of CBOR data`

**Comment by Kamil93** [comment]
My bad, should be:

`const encoded_trimmed = new Uint8Array(encoded.buffer.slice(encoded.byteOffset, encoded.byteOffset + encoded.byteLength));`

and you can also send raw `ArrayBuffer`:

`encoded.buffer.slice(encoded.byteOffset, encoded.byteOffset + encoded.byteLength)`

but still you have to chop the encoded output before sending it. It must be related to engine.io, but may be to browsers WebSocket as well.

**Comment by kriszyp** [comment]
I tested this, and definitely seems like using `websocket.send(data)` with `data` being a Uint8Array that consists of a subset of an ArrayBuffer seems to work fine (for example, if the Uint8Array data is 4 bytes and the ArrayBuffer is 64 bytes, it only sends 4 bytes). Perhaps this is a bug with socket.io, since WebSocket itself seems to work? Or do you have a more complete example?

**Comment by pvh** [comment]
Just a note @kriszyp that I have seen similar behaviour with vanilla websocket and use a similar incantation to what @Kamil93 shows above as a workaround.

**Comment by kriszyp** [comment]
@pvh You are saying that if you do `webSocket.send(typedArray.subarray(start, end))` (with an instance of a `WebSocket` and a subarray of the backing `ArrayBuffer` like cbor-x does) it will send bytes outside of the specified `start` and `end` range?
