### ISSUE TITLE
BigUInt64Array is not working on iPhones

### ISSUE THREAD

**Issue by killkli** [kriszyp/cbor-x#19]
Safari on iPhones don't implement BigUInt64Array. Using cbor-x with browsers on these device would cause the web app to break. Similar issue can be found on ChromeLab's jsbi project here:
https://github.com/tweag/asterius/issues/792

Might be some way to avoid this problem?

**Comment by killkli** [comment]
Ooops, the problem is not with decoder (since I didn't actually used 64 types), but with type Arrays used in encoder.js.
There the code included all typed Arrays which is great but two typed Array is not supported on iPhones (before iOS15):
BigInt64Array & BigUint64Array. 
The line here caused the application to halt on my iOS 14 devices. 
https://github.com/kriszyp/cbor-x/blob/0efaf162c3201926f8f842c6bf62ca9d9fdd198e/encode.js#L741-L743

Although the problem would be solved once I upgraded the device to iOS 15, still....

**Comment by killkli** [comment]
BTW, the code runs on older iphone devices (yet I'm not certain would there be some problems or not) once I removed BigUint64Array & BigInt64Array from the list.

**Comment by kriszyp** [comment]
Ah, ok, thank you for the clarification, I will fix that.

**Comment by kriszyp** [comment]
Fix published in v0.9.3.
