### ISSUE TITLE
Exception: Data read but end of buffer not reached

### ISSUE THREAD

**Issue by devtrix** [kriszyp/cbor-x#21]
I am trying to decode a cbor string. I used TextEncoder to convert it to Uint8Array and used the decode function when I get this error.
index.js:138 Uncaught (in promise) Error: Data read, but end of buffer not reached
    at checkedRead (index.js:138)
    at Object.decode (index.js:86)
    
Please help.

**Comment by kriszyp** [comment]
This generally means that the input data is not valid. You created a valid CBOR binary to pass into decode? Here is an example of how you would create a (valid) CBOR encoding using `TextEncoder`:
```
let te = new TextEncoder();
let bytes = new Uint8Array(64);
bytes[0] = 0x78; // one-byte string length encoding
// encode the string, starting at the third byte and store the length:
let stringBytes = te.encodeInto('Hello, World!', bytes.subarray(2)).written;
bytes[1] = stringBytes; // store the length in the string prefix
decode(bytes.subarray(0, stringBytes + 2)); -> 'Hello, World!'
```
Do you have a sample of your code that is failing?

**Comment by devtrix** [comment]
I definitely was not doing this.  So let me explain what I am trying to do here.  I am working wit a crypto wallet and it gives me a 124 char CBOR encoded string.  I need to decode that string so parts of it can be used for validation.  So I tried to convert it to a Uint8Array as your decode method didnt work with a string. 
Here is the string:
821a00159282a1581c00b96929c38ef48107f18e3122873b43de6182c9355aae4110ce3d33a15654657374436f6c6c656374696f6e3030566f6c33343101

This is not sensitive info, just FYI.
Any help is appreciated.

**Comment by kriszyp** [comment]
You would need to first convert the hex string to binary bytes (there are lot of different types of string/binary encodings). If you are working in NodeJS you could just decode the hex string to a buffer by specifying it as the string encoding:
```
let bytes = Buffer.from('821a00159282a1581c00b96929c38ef48107f18e3122873b43de6182c9355aae4110ce3d33a15654657374436f6c6c656374696f6e3030566f6c33343101', 'hex');
decode(bytes); // bytes is a valid CBOR and can be decoded
```
If you are not working Node, there are plenty of examples of how to convert a hex to a Uint8Array like:
```
const fromHexString = hexString =>
  new Uint8Array(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
```
I don't really know what the returned CBOR structure means, but I assume it means something to you.

**Comment by devtrix** [comment]
First of all, thank you so much for your help.  I am doing this on the browser only at this point. I have a different issue now.  The 'fromHexString' when passed was still a function and that's the error message I got saying t must be a Uint8Array but was a function.  So I did create a function and verified it was a byte array, it still gives the same error.  Here is my code.

function hexToBytes(hex) {
    for (var bytes = [], c = 0; c < hex.length; c += 2)
        bytes.push(parseInt(hex.substr(c, 2), 16));
    return bytes;
}
------------------------------------------------------------------------
// data is the raw hex strig
const fromHexString = hexToBytes(data);                         
                                             console.log(fromHexString);
                let txt = CBOR.decode(fromHexString); 
                console.log(txt);

**Comment by devtrix** [comment]
So what I am getting back is
[
    1413762,
    {
        "0,185,105,41,195,142,244,129,7,241,142,49,34,135,59,67,222,97,130,201,53,90,174,65,16,206,61,51": {
            "84,101,115,116,67,111,108,108,101,99,116,105,111,110,48,48,86,111,108,51,52,49": 1
        }
    }
]

I need code to do something like this that happens on cbor.me.  
I paste the hex string on the right side, select "as text" checkbox and click the left arrow button [<--] where it displays the word Bytes.  I want my object (output) to look like the left side.

Thanks in advance.

**Comment by kriszyp** [comment]
Your CBOR structure is a map where the keys are binary data. This doesn't really have a clear JS equivalent, because JS requires that object keys be strings (or symbols or numbers), not typed arrays (like Uint8Array). So in the browser, if you are using the default setting where maps are mapped to objects, the typed array just gets coerced to a string ("0,185,105,41,195,...").

> My question is, what is this an array(?) of?: "0,185,105,41,195,142,244

I have no idea, this is the binary data for the key that came from your data. It is the decimal representation of that binary data (and 00B96929C38EF48... is the hexadecimal representation of that same binary data).

If you want to preserve the original keys, you may want to consider mapping the CBOR map structures to JS Maps, which _will_ preserve the original binary data:
```
let decoder = new CBOR.Decoder({ mapsAsObjects: false });
let decoded = decoder.decode(bytes);
let firstKey = Array.from(decoded[1].keys())[0] -> first key as a Uint8Array
let secondKey = Array.from(decoded[1].get(firstKey).keys())[0] -> second key as Uint8Array
new TextDecoder().decode(secondKey) -> decode second to a string
```

**Comment by devtrix** [comment]
Thanks a million.  You are the best! Thank you for your patience, kindness and absolute brilliance.  Needless to say you very quick responses.  My hats off to you. 

You said
>I have no idea, this is the binary data for the key that came from your data. It is the decimal representation of that binary data >(and 00B96929C38EF48... is the hexadecimal representation of that same binary data).
How can I get that hex representation?

**Comment by ledlamp** [comment]
they said it was cbor >:( 

![Image](https://github.com/user-attachments/assets/d8abda26-68b9-4089-ba7e-43a5eda87f44)
