### ISSUE TITLE
feat: support shared/web workers

### ISSUE THREAD

**Issue by intech** [kriszyp/cbor-x#25]
`window` and `global` is not defined:
https://github.com/kriszyp/cbor-x/blob/2248b479b943fbf3ac6ea2049cb6e4c2ea14ed39/decode.js#L760
Need use `self` in workers

**Comment by intech** [comment]
@kriszyp please, tell me the best way to contribute to solve this problem, do you have any ideas?

**Comment by kriszyp** [comment]
Ok, should be fixed, and published in v1.0.0.
