### ISSUE TITLE
Decoding support for little endian typed arrays

### ISSUE THREAD

**Issue by DavidXenakis** [kriszyp/cbor-x#30]
Would it be possible for cbor-x to support big endian typed array? It looks like only little endian typed arrays are supported, currently.

**Comment by kriszyp** [comment]
What kind JS typed array would you serialize this from (or deserialize them into)? All the multi-byte typed arrays in JS are little-endian (well, platform dependent, but not many big endian machines these days). Are you thinking that there would be some flag for cbor-x to indicate that a typed array like Uint32Array should have all of its words reversed when serialized? Or are you just looking for support for the big-endian type array tags to be deserialized into standard JS typed arrays? (or even into a plain array?)

**Comment by DavidXenakis** [comment]
Hi Kris, thanks for the reply! The specific use-case I'm facing is purely deserialization of big-endian typed arrays into standard JS typed arrays. I'm trying to migrate my project from the `cbor` package to the `cbor-x` package. My initial tests surfaced the fact that some of the data my project consumes is serialized as big-endian.

**Comment by kriszyp** [comment]
And also, to make sure I am clear, your existing data is serialized with the big endian typed array tags like tag 65, 66, 67, etc. (from https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml), right?

**Comment by DavidXenakis** [comment]
Ah, my sincerest apologies. I definitely meant to be asking about supporting little endian typed arrays. The data comes in with tag 85, which isn't supported.

**Comment by kriszyp** [comment]
Oh, I see, I put the incorrect tag (81) on the Float32 and Float64 typed arrays. Ok, I'll fix that.

**Comment by kriszyp** [comment]
Fixes for float typed arrays, as well as big endian support should be available in v1.2.0.

**Comment by DavidXenakis** [comment]
Thank you so much for your quick response and fix for this!
