### ISSUE TITLE
Explicit Map type support

### ISSUE THREAD

**Issue by Bluebie** [kriszyp/cbor-x#5]
For use with structured cloning, it's sometimes necessary to preserve the type difference between a javascript Object (with string keys) and a Map (with any type keys).

It would be useful in some applications to be able to explicitly support Map's as a distinct type from string-keyed objects. A spec for this including rationale is at: <https://github.com/shanewholloway/js-cbor-codec/blob/master/docs/CBOR-259-spec--explicit-maps.md>

cbor-x currently can't support this use case, because it doesn't check user supplied extension types until after it checks if a value is a Map, and provides it's own generic encoding.

cbor-x should do one of:
- allow users to register map types, and correctly use the provided encode and decode functions, by checking for extensions before falling back to it's built in Map encoding
- provide built in support for explicit maps, via an option, like it does for Set.
- or throw an error if a user tries to register Map as an extension type, to make it clear why it's not working and that custom map encoding is not supported.

**Comment by kriszyp** [comment]
cbor-x actually can and does preserve the type difference between objects and maps when record tags are used; the explicit is in reverse though, Javascript `Map`s are mapped to CBOR map types (which seems like an obvious/reasonable mapping), and JS objects are explicitly tagged as records. However, it is quite reasonable to use tag 259 for maps, particularly for the case when object/record tags are disabled.

The referenced commit adds support for explicitly specifying a map with the 259 tag with the `useTag259ForMaps` options. This is enabled by default when record tags are disabled.

**Comment by kriszyp** [comment]
This is published in v0.8.3.
