### ISSUE TITLE
Problems with cbor-x streaming decoding

### ISSUE THREAD

**Issue by Bluebie** [kriszyp/cbor-x#7]
I feel like there's a bunch of little related issues with Decoder which require an exhaustive test driven development approach if cbor-x is going to continue offering a streaming decoder or iterator interface in the future. I have an iterator implementation written which seems to work well aside from these underlying problems.

- [ ] incomplete strings are decoded as a string with the correct length, padded with \u0000 null codepoints for the bytes which weren't available in the chunk being decoded. This needs to throw an incomplete error
- [ ] multibyte varint integer numbers when not all the bytes needed for decode, needs to throw incomplete error, instead throws a "RangeError: Offset is outside the bounds of the DataView"
- [ ] incomplete buffers/byte arrays, similar to strings, are padded with 0 nul bytes for the section that is missing in the chunk being processed, but need to throw an incomplete error
- [ ] bigints with missing bytes throw the same RangeError as regular ints
- [ ] arrays with explicit up front length are padded with integer 0 values when values are missing from the chunk
- [ ] incomplete Set chunks are decoded as a plain empty object `{}` (so weird??)
- [ ] partial objects sometimes decode in funky ways with `"0"` keys and `0` values, and sometimes decode as an empty object

#6 provides a minimal test of the above problems.

Things that still need testing:

- [ ] what happens to an array with prefixed length, where the length itself is incomplete?
- [ ] as above with object/map?
- [ ] what about indefinite length objects/map, arrays, buffers, strings where there is no break stop code?
- [ ] Is there a behaviour difference when these problems are nested deeply inside of maps, arrays, or other nesting structures?

Things to think about:

- [ ] Is there a better approach to resumable stream decoding where we might not need to throw away all the work done to decode a chunk, only to do it again next time a chunk arrives? When large objects come through streams like network sockets which have relatively small packet sizes (on the order of 1.5kb) cbor-x may end up attempting to fully decode an object dosens, hundreds, maybe thousands of times before it has enough information to return a value? It would be great to be able to hold everything that was decodable in memory, and pause, and resume when another chunk comes in that can expand the buffer's length.

**Comment by kriszyp** [comment]
I believe these problems have all been fixed (and mostly tested) now, and are published in v0.8.3. Let me know if you see any remaining issues.

As far as a "resumable" parser, that would be a bigger project, and it isn't clear if the cost of additional complexity may actually reduce performance for typical use cases more than acceptable, but still may be worth exploring at some point.
