### ISSUE TITLE
globalThis not available on older Safari versions

### ISSUE THREAD

**Issue by headlessme** [kriszyp/cbor-x#78]
The `globalThis` variable is not available on older versions of Safari (pre 12.2) and leads to a crash in this library.

https://github.com/kriszyp/cbor-x/blob/6626470d3ae71ec94b057a444fccc02e94fcc4b0/encode.js#L7

Looks like it was introduced recently:

https://github.com/kriszyp/cbor-x/commit/d4072fe73b9df877f081b21c8956dbdb7bd9985f

Browser compatibility: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility

**Comment by headlessme** [comment]
@kriszyp thanks so much for the quick update! Could you publish to NPM?

**Comment by kriszyp** [comment]
Oops, sorry for being slow, this should be published in v1.5.3.

**Comment by al-the-x** [comment]
@headlessme @kriszyp according to https://www.npmjs.com/package/cbor-x, 1.5.3 is public. Safe to close this?

We were also waiting for this update...
